# Generated by Django 2.2.12 on 2020-12-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=50, null=True)),
                ('nama_barang', models.CharField(max_length=50)),
                ('group_id', models.CharField(max_length=150)),
                ('spesifikasi', models.CharField(max_length=250)),
                ('jumlah', models.IntegerField(default=0, null=True)),
                ('landasan_kebutuhan', models.CharField(max_length=350)),
                ('gambar', models.ImageField(null=True, upload_to='gambar/')),
                ('nomor_memo', models.CharField(max_length=20)),
                ('tanggal_memo', models.DateField(null=True)),
                ('perihal_memo', models.CharField(max_length=150)),
                ('harga_barang', models.PositiveIntegerField(null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('jumlah2', models.IntegerField(default=0, null=True)),
                ('tl', models.IntegerField(default=0, null=True)),
                ('htl', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemilik', models.CharField(max_length=60)),
                ('divisi', models.CharField(max_length=80)),
                ('merk', models.CharField(max_length=150)),
                ('jabatan', models.CharField(max_length=150)),
                ('nomor_barang', models.IntegerField(default=0, null=True)),
                ('tanggal_terima', models.DateField(null=True)),
                ('tipe', models.CharField(max_length=150)),
                ('nama_penyerah', models.CharField(max_length=90)),
                ('pemimpin_user', models.CharField(max_length=80)),
                ('pemimpin_pgo', models.CharField(max_length=85)),
                ('pengajuans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengajuan.Pengajuan')),
            ],
        ),
    ]
