# Generated by Django 2.2.12 on 2020-12-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terima',
            name='nomor_barang',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
